micronaut:
  application:
    name: pet_shop_kotlin_lab
  server:
    port: 8080
datasources:
  default:
    url: jdbc:postgresql://teste-postgres-compose:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'Postgres2020@#'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
